### ISSUE TITLE
Some small website issues

### ISSUE THREAD

**Issue by hermanTenuki** [laudep/code-gif-generator#56]
Hi, just found out this great package, surprised that it still has no attention from community.

By the way, i encountered 2 issues when using it at your website (didn't tried to use actual package manually):
- When pressing `BACKSPACE` or `ENTER` keys, `GENERATE GIF` button is becoming disabled and i can't actually use it until i write something, even if there is actually text in input window;
- Some lines at the bottom of original text is cutting out in gif, so i need to put some additional lines at the end.

Examples of second problem:
 ![Screenshot_1](https://user-images.githubusercontent.com/54952579/101991841-59a05800-3cc0-11eb-90eb-3bdfca5832e8.jpg)
25 lines of input and gif with only one frame with 21 lines.

![Screenshot_2](https://user-images.githubusercontent.com/54952579/101991843-5a38ee80-3cc0-11eb-977b-ee779b579192.jpg)
32 lines of input and gif with frames showing 1-26 lines

**Comment by laudep** [comment]
Thanks for the feedback, Herman!

I have updated the website with a fix for the first issue.
The second issue has been patched with a workaround for now but needs another look.

Do let me know if you have any further remarks or suggestions.
